#Make File


protoc:
    --proto_path=internals/proto \
    --go_out=internals/proto --go-grpc_out=internals/proto \
    --go_opt=paths=source_relative --go-grpc_opt=paths=source_relative \
    --grpc-gateway_out=internals/proto --grpc-gateway_opt=logtostderr=true --grpc-gateway_opt=paths=source_relative \
    internals/proto/movie.proto

