#Make File

# Define the binary output directory
BIN_DIR = bin
MIGRATE_BIN = $(BIN_DIR)/migrate
SERVER_GO = cmd/server/main.go
CLIENT_GO = cmd/client/main.go

all: build up run_server run_client protoc

build:
	mkdir -p $(BIN_DIR)
	go build -o $(MIGRATE_BIN) ./cmd/migrations

up: build
	$(MIGRATE_BIN) up

clean:
	rm -rf $(BIN_DIR)

run_server:
	go run $(SERVER_GO)

run_client:
	go run $(CLIENT_GO)

protoc:
    --proto_path=internals/proto \
    --go_out=internals/proto --go-grpc_out=internals/proto \
    --go_opt=paths=source_relative --go-grpc_opt=paths=source_relative \
    --grpc-gateway_out=internals/proto --grpc-gateway_opt=logtostderr=true --grpc-gateway_opt=paths=source_relative \
    internals/proto/movie.proto

