[server]
    host = "localhost"
    port = "8080"

[client]
    host = "localhost"
    port = "5050"

[external]
    baseurl = "https://freetestapi.com/api"
    version = "v1"
    endpoint = "movies"

[database]
    driver = "postgres"
    host = "localhost"
    port = 5432
    user = "movie_user"
    password = "password@123"
    dbname = "movies_db"
    sslmode = "disable"

